rbac:
  create: false
  ## Use an existing ClusterRole/Role (depending on rbac.namespaced false/true)
  # useExistingRole: name-of-some-(cluster)role
  pspEnabled: false
  pspUseAppArmor: false

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: false
  inMemory:
    enabled: true

adminUser: admin
adminPassword: password

persistence:
  type: statefulset
  enabled: true
  storageClassName: local-path
  
