apiVersion: v1
kind: Secret
metadata:
  name: homelab-observability-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/lostinopensrc/homelab-observability-applicationset.git